---

- name: restart ipsec
  service:
    name: ipsec
    stage: restarted

- name: reload ipsec
  service:
    name: ipsec
    state: reloaded

- name: reload groups
  command: ipsec auto --rereadgroups

- name: reload secrets
  command: ipsec whack --rereadsecrets

